linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    check-shadowing: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - scopelint
        - prealloc
